// pages/_app.tsx
import { Amplify } from "aws-amplify";
import config from "@/amplifyconfiguration.json";
import type { AppProps } from "next/app";
import { generateClient } from "aws-amplify/api";
import { type Schema } from "@/amplify/data/resource";
import "@aws-amplify/ui-react/styles.css";
import { Authenticator } from "@aws-amplify/ui-react";

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config, { ssr: true });

export const client = generateClient<Schema>();

function App({ Component, pageProps }: AppProps) {
  return (
    <Authenticator.Provider>
      <Component {...pageProps} />
    </Authenticator.Provider>
  );
}

export default App;
