"use client";

import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { withAuthenticator } from "@aws-amplify/ui-react";
import type { WithAuthenticatorProps } from "@aws-amplify/ui-react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

function Home({ user, signOut }: WithAuthenticatorProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <button onClick={signOut}>Sign Out</button>
          <p>Welcome, {user?.username}!</p>
          <h1>Amplify Gen2</h1>
        </div>

        <Link href={"/blogs"}>Blogs</Link>
      </main>
    </>
  );
}

export default withAuthenticator(Home);
