"use client";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { generateClient } from "aws-amplify/data";
import { type Schema } from "@/amplify/data/resource";
import { useEffect, useState } from "react";
import { useAuthenticator } from "@aws-amplify/ui-react";

const client = generateClient<Schema>(); // use this Data client for CRUDL requests

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { username, signOut } = useAuthenticator();
  const [todos, setTodos] = useState<Schema["Todo"][]>([]);

  async function listTodos() {
    // fetch all todos
    const { data } = await client.models.Todo.list({ authMode: "apiKey" });
    setTodos(data);
  }

  useEffect(() => {
    listTodos();

    const sub = client.models.Todo.observeQuery().subscribe(({ items }) =>
      setTodos([...items])
    );

    return () => sub.unsubscribe();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <button onClick={signOut}>Sign Out</button>
          <p>Welcome, {username}!</p>
          <h1>Amplify Gen2</h1>
          <button
            style={{ marginTop: "1em", padding: ".5em 1em" }}
            onClick={async () => {
              await client.models.Todo.create({
                content: window.prompt("Enter title:"),
                priority: "medium",
              });
            }}
          >
            Create Todo
          </button>
        </div>
        <div>
          <h2>Todos</h2>

          {todos.map((todo) => {
            return (
              <div key={todo.id} style={{ margin: "1em auto" }}>
                {todo.content}
                <button
                  style={{ marginLeft: "1em" }}
                  onClick={async () => {
                    await client.models.Todo.delete({ id: todo.id });
                  }}
                >
                  Delete
                </button>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}
